### ISSUE TITLE
How

### ISSUE THREAD

**Issue by useunreal** [voldemortX/DST-CBC#5]
First of all, thank you very much for your previous help. Now I can train on my own data set, but now I have another problem. I want to convert the output of the network into a mask file like the given label. I want to know how this should be How to do it, can you help me? Can the output use softmax and then set the threshold to generate the final mask?

**Comment by voldemortX** [comment]
@useunreal I think you can go on without changing the pseudo labeling code since they should not be affected? Anyways, you can refer to [this function](https://github.com/voldemortX/DST-CBC/blob/53853f63033fdb88206828a72d960de2c03efd69/segmentation/utils/common.py#L182) and the one it calls. Concretely, I store pseudo labels with [2 channels](https://github.com/voldemortX/DST-CBC/blob/53853f63033fdb88206828a72d960de2c03efd69/segmentation/utils/common.py#L167): the predicted class (e.g. 0-18, 255) & softmaxed confidence of the predicted class. All unselected pixels are marked by class 255. Also, I store predictions in the same resolution as the original images by cropping [here](https://github.com/voldemortX/DST-CBC/blob/53853f63033fdb88206828a72d960de2c03efd69/segmentation/utils/common.py#L159).

**Comment by voldemortX** [comment]
If you want to save pseudo labels as png files, you'd need to first set the 255s and then store them with colors.

**Comment by useunreal** [comment]
Thank you for your patient answers, thank you very much

**Comment by voldemortX** [comment]
Since the question was resolved a long time ago, this issue is now closed. Feel free to reopen if there are further questions.
